force-app/main/default/objects/ApiCallout__c/ApiCallout__c.object-meta.xml
<CustomObject>
    <label>ApiCallout</label>
    <nameField>
        <displayFormat>API-{0000000000}</displayFormat>
        <label>ApiCallout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApiCallouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApiCallout__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ApiCallout__c/fields/RequestUrl__c.field-meta.xml
<CustomField>
    <fullName>RequestUrl__c</fullName>
    <label>RequestUrl</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApiCallout__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ApiCallout__c/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <label>ResponseStatusCode</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApiCallout.cls
public without sharing class ApiCallout {
    public ApiCallout() {

    }

    public HttpResponse send(HttpRequest request) {
        Http http = new Http();
        HttpResponse response = http.send(request);

        // Success
        if (response.getStatusCode() < 300 ) {
            return response;
        }

        // Error
        LogError(request, response);
        return response; 
    }

    private static void LogError(HttpRequest request, HttpResponse response) {
        ApiCallout__c api = new ApiCallout__c();
        api.RequestUrl__c = request.getEndpoint();  
        api.Request__c = request.toString();  
        api.Response__c = response.toString();    
        api.ResponseStatusCode__c = response.getStatusCode();        
        insert api;
    }
}